#!/bin/bash

download_dir="/home/chicco/Downloads/"
audio_dir="$download_dir/audio"
image_dir="$download_dir/image"
archive_dir="$download_dir/archive"
code_dir="$download_dir/code"
uncategorized_dir="$download_dir/uncategorized"
osu_dir="/home/chicco/.local/share/osu-wine/osu!/Songs"
text_dir="$download_dir/text"
appimage_dir="$download_dir/appimages"
video_dir="$download_dir/videos"
windows_dir="$download_dir/windows"

mkdir -p "$audio_dir" "$image_dir" "$archive_dir" "$code_dir" "$uncategorized_dir" "$osu_dir" "$text_dir" "$appimage_dir" "$video_dir" "$windows_dir"

log_file="$download_dir/download_log.txt"
echo "Inizio del processo di suddivisione dei file." > "$log_file"

audio_formats=("mp3" "wav" "flac")
image_formats=("jpg" "jpeg" "png" "gif")
video_formats=("mp4")
archive_formats=("zip" "rar" "tar.gz" "tar.xz" "jar" "iso")
code_formats=("sh" "c" "cpp" "py" "html" "css" "ino")
text_formats=("doc" "docx" "xls" "xlsx" "ppt" "pptx" "txt" "pdf")
appimage_formats=("AppImage")
windows_formats=( "exe" "msi" )

while true; do
  for file in "$download_dir"/*; do
    if [[ -f "$file" ]]; then
      filename=$(basename "$file")
      extension="${filename##*.}"

      if [[ "${audio_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$audio_dir/$filename"
        echo "Spostato $filename in $audio_dir" >> "$log_file"
      elif [[ "${image_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$image_dir/$filename"
        echo "Spostato $filename in $image_dir" >> "$log_file"
      elif [[ "${video_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$video_dir/$filename"
        echo "Spostato $filename in $video_dir" >> "$log_file"
      elif [[ "${archive_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$archive_dir/$filename"
        echo "Spostato $filename in $archive_dir" >> "$log_file"
      elif [[ "${code_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$code_dir/$filename"
        echo "Spostato $filename in $code_dir" >> "$log_file"
      elif [[ "${windows_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$windows_dir/$filename"
        echo "Spostato $filename in $windows_dir" >> "$log_file"
      elif [[ "$extension" == "osr" ]]; then
        if pgrep -x "osu.exe" > /dev/null; then
          mv "$file" "$osu_dir/$filename"
          echo "Spostato $filename in $osu_dir perché osu.exe è in esecuzione" >> "$log_file"
        else
          mv "$file" "$uncategorized_dir/$filename"
          echo "Spostato $filename in $uncategorized_dir" >> "$log_file"
        fi
      elif [[ "${text_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$text_dir/$filename"
        echo "Spostato $filename in $text_dir" >> "$log_file"
      elif [[ "${appimage_formats[*]}" =~ "$extension" ]]; then
        mv "$file" "$appimage_dir/$filename"
        echo "Spostato $filename in $appimage_dir" >> "$log_file"
      else
        if [[ -d "$file" || "$filename" == "crdownload" || "$filename" == "torrent" ]]; then
          continue
        else
          mv "$file" "$uncategorized_dir/$filename"
          echo "Spostato $filename in $uncategorized_dir" >> "$log_file"
        fi
      fi
    fi
  done

  echo "Attesa per 2 secondi prima di ripetere il processo..." >> "$log_file"
  sleep 2
done
